---
- hosts: drupalbox
  vars:
    hostname: drupalbox
    rvm1_user: vagrant
    rvm1_install_path: /home/vagrant/.rvm
    php_xdebug_enabled: true
    php_ini_sendmail_path: "/usr/local/bin/mhsendmail"
  vars_files:
    - vars/default/common.yml
    - vars/dev/mysql.yml
    - vars/dev/apache.yml
    - vars/dev/php.yml
  roles:
    - { role: init }
    - { role: common }
    - { role: openssh }
    - { role: git }
    - {
        role: rvm1_io.ruby,
        tags: ruby,
        become: yes
      }
    - { role: memcached }
    - { role: mailhog }
    - { role: apache }
    - { role: mysql-client }
    - { role: mysql-server }
    - { role: php7 }
    - { role: composer }
    - { role: phpmyadmin }
    - { role: nodejs }
    - { role: phantomjs }
    - { role: duplicity }
    - { role: drupalbox }
