---
- hosts: drupalbox
  vars:
    hostname: drupalbox
    rvm1_user: vagrant
    rvm1_install_path: /home/vagrant/.rvm
    php_xdebug_enabled: true
    php_ini_sendmail_path: "/usr/local/bin/mhsendmail"
    jetty_server_enabled: false
    jetty_server_java_options: "-Xmx256m -Djava.awt.headless=true -Dsolr.solr.home=/usr/share/solr/current"
    solr_cores:
      - name: drupal7
        folder: search_api_solr-7x-1.11-4.x
      - name: drupal8
        folder: search_api_solr-8x-1.0-alpha5-4.x
  vars_files:
    - vars/default/common.yml
    - vars/dev/mysql.yml
    - vars/dev/apache.yml
    - vars/dev/php.yml
  roles:
    - { role: init }
    - { role: common }
    - { role: openssh }
    - { role: git }
    - {
        role: rvm1_io.ruby,
        tags: ruby,
        become: yes
      }
    - { role: memcached }
    - { role: mailhog }
    #- { role: jetty9 }
    #- { role: solr }
    - { role: apache }
    - { role: mysql-client }
    - { role: mysql-server }
    - { role: php7 }
    - { role: composer }
    - { role: phpmyadmin }
    - { role: nodejs }
    - { role: phantomjs }
    - { role: duplicity }
    - { role: drupalbox }
