---
- hosts: drupalbox
  vars:
    hostname: drupalbox
    php_xdebug_enabled: true
    php_ini_sendmail_path: "/usr/local/bin/mhsendmail"
  vars_files:
    - vars/default/common.yml
    - vars/dev/mysql.yml
    - vars/dev/apache.yml
    - vars/dev/php.yml
  roles:
    - { role: init }
    - { role: common }
    - { role: openssh }
    - { role: git }
    -
      role: rvm.ruby
      tags: ruby
      become: yes
      rvm1_user: vagrant
      rvm1_install_path: /home/vagrant/.rvm
      rvm1_rubies:
        - 'ruby-2.5.2'
    - { role: memcached }
    - { role: mailhog }
    - {
        role: geerlingguy.java,
        become: yes
      }
    - {
        role: geerlingguy.solr,
        solr_version: "7.7.2",
        solr_cores: ['example'],
        become: yes
      }
    # This role collides with geerlingguy.solr.
    # We need to reconcile how to install from our preferred config.
    - {
        role: solr-configuration,
        become: yes
      }
    - { role: apache }
    - { role: mysql-client }
    - { role: mysql-server }
    - { role: php7 }
    - { role: composer }
    - { role: phpmyadmin }
    - { role: nodejs }
    - { role: phantomjs }
    - { role: duplicity }
    - { role: drupalbox }
