%w{ vagrant-hostmanager vagrant-auto_network }.each do |plugin|
    unless Vagrant.has_plugin?(plugin)
        raise "#{plugin} plugin is not installed. Please install with: vagrant plugin install #{plugin}"
    end
end

Vagrant.configure("2") do |config|
  config.vm.box = "palantir/drupalbox"
  #config.vm.box = "palantir/ubuntu1404"
  config.vm.box_version = ">= 2.0.0, < 3.0.0"
  config.vm.hostname = "drupalbox.local"

  config.vm.network "private_network", :auto_network => true
  config.vm.synced_folder ".", "/vagrant", :nfs => true

  config.ssh.forward_agent = true

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "1024"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", 1024]
  end

  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "../provisioning/drupalbox.yml"
  #   ansible.groups = {
  #     "drupalbox" => "default",
  #   }
  # end
end
