---

- name: Solr Configuration | Copy Solr config
  copy:
    src: templates/solr_7.x_config
    dest: /tmp/

- name: Solr Configuration | Install 'drupal8' Solr core
  command:
    cmd: /opt/solr/bin/solr create_core -c drupal8 -d /tmp/solr_7.x_config
    creates: /var/solr/data/drupal8
  become: yes
  become_user: solr
