# This Vagrantfile can be used to test the drupalbox Ansible playbook.

box_name    = 'drupalbox'
box_base    = 'geerlingguy/ubuntu1604'
box_version = '~> 1.0'

%w{ vagrant-hostmanager vagrant-auto_network vagrant-serverspec }.each do |plugin|
    unless Vagrant.has_plugin?(plugin)
        raise "#{plugin} plugin is not installed. Please install with: vagrant plugin install #{plugin}"
    end
end

Vagrant.configure("2") do |config|
  config.vm.box = "#{box_base}"
  config.vm.box_version = "#{box_version}"
  config.vm.hostname = "#{box_name}.local"

  config.vm.network "private_network", :auto_network => true
  config.vm.synced_folder ".", "/vagrant", :nfs => true

  config.ssh.forward_agent = true

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "1024"
  end

  config.vm.provision "ansible", type: :ansible do |ansible|
    ansible.playbook = "../#{box_name}/#{box_name}.yml"
    ansible.galaxy_role_file = "../#{box_name}/requirements.yml"
    ansible.groups = {
      "#{box_name}" => "default",
    }
  end

  config.vm.provision "test", type: :serverspec do |spec|
    spec.pattern = "../#{box_name}/tests/*_spec.rb"
  end

end
