---

- name: Add apt-repository
  become: yes
  apt_repository:
    repo: "ppa:ondrej/php"
  tags: php5

- name: Install PHP
  become: yes
  apt:
    name:
      - php7.3-cli
      - php7.3-fpm
      - libapache2-mod-php7.3
      - php-pear
      - php7.3-common
      - php7.3-dev
      - php-console-table
    state: latest
  tags: php7

- name: Install PHP Modules
  become: yes
  apt:
    name: "{{ php7_modules }}"
    state: latest
  tags: php7

- name: Enable Modules
  become: yes
  shell: /usr/sbin/phpenmod {{ item }}
  with_items: "{{ php7_modules_enable }}"
  tags: php7

- name: Enable Apache Module
  become: yes
  command: /usr/sbin/a2enmod php7.3
  tags: php7

- name: Update php.ini (cli)
  become: yes
  template: src=php.ini.j2 dest={{ item }} owner=root group=root
  with_items:
    - /etc/php/7.3/cli/php.ini
    - /etc/php/7.3/fpm/php.ini
  tags: php7

- include: pecl.yml

- include: xdebug.yml

- name: Restart Apache
  become: yes
  service:
    name: apache2
    state: restarted
  tags: php5
