---
- name: Solr Cleanup | Replace systemd script for Solr 4
  template:
    src: solr4.unit.j2
    dest: /etc/systemd/system/solr.service
    owner: root
    group: root
    mode: 0755

- name: Solr Cleanup | Fix log permissions
  file:
    path: /var/log/solr.log
    owner: solr
    group: adm

- name: Solr Cleanup | Reload daemon
  shell: systemctl daemon-reload

- name: Solr Cleanup | Restart Solr
  service:
    name: solr
    state: restarted
    enabled: no

- name: Solr Cleanup | Enable Solr start on boot
  service:
    name: solr
    enabled: yes

- name: Solr Cleanup | Download Solr configuration for Drupal 7
  get_url:
    url: https://ftp.drupal.org/files/projects/search_api_solr-7.x-1.12.tar.gz
    dest: /tmp/search_api_solr-7.x-1.12.tar.gz

- name: Solr Cleanup | Download Solr configuration for Drupal 8
  get_url:
    url: https://ftp.drupal.org/files/projects/search_api_solr-8.x-1.2.tar.gz
    dest: /tmp/search_api_solr-8.x-1.2.tar.gz
