---
- name: Duplicity | Add PPA
  become: yes
  apt_repository: repo='ppa:duplicity-team/ppa'
                  state=present
  tags: duplicity

- name: Duplicity | Update apt cache
  become: yes
  apt:
    update_cache: yes
  tags: duplicity

- name: Duplicity | Install System Packages
  become: yes
  apt:
    pkg:
      - duplicity
      - duply
      - python-boto
    state: installed
  tags: duplicity
