---
- name: Memcached | Install Memcached
  become: yes
  apt:
    name:
      - memcached
      - libmemcached-tools
    state: present
    update_cache: yes
  tags: memcached

- name: Memcached | Configure Memcached
  become: yes
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
    owner: root
    group: root
    mode: 0644
  tags: memcached

- name: Memcached | Restart Memcached
  become: yes
  service:
    name: memcached
    state: restarted
  tags: memcached

- name: Memcached | Enable Memcached
  become: yes
  service:
    name: memcached
    state: started
    enabled: yes
  tags: memcached
