---
- name: PhantomJS | Install firefox
  become: yes
  apt: pkg=iceweasel
       state=present
       update-cache=yes
  tags: phantomjs

- name: PhantonJS | Install fontconfig
  become: yes
  apt: pkg=fontconfig
       state=present
  tags: phantonjs

- name: PhantomJS | Create home directory
  become: yes
  file: path=/usr/local/src/phantomjs
        state=directory
  tags: phantomjs

- name: PhantomJS | Download phantomjs
  become: yes
  get_url: url=https://bitbucket.org/ariya/phantomjs/downloads/{{ phantomjs }}.tar.bz2
           dest=/usr/local/src/phantomjs/{{ phantomjs }}.tar.bz2
  tags: phantomjs

- name: PhantomJS | Untar phantomjs
  become: yes
  shell: tar xjf {{ phantomjs }}.tar.bz2
         chdir=/usr/local/src/phantomjs
         creates=/usr/local/src/{{ phantomjs }}
  tags: phantomjs

- name: PhantomJS | Symlink the phantomjs executable
  become: yes
  file: dest=/usr/local/bin/phantomjs
        src=/usr/local/src/phantomjs/{{ phantomjs }}/bin/phantomjs
        state=link
  tags: phantomjs

- name: PhantomJS | Upstart PhantomJS
  become: yes
  template: src=upstart/phantomjs.conf.j2 dest=/etc/init/phantomjs.conf
  when: ansible_distribution_version == '14.04'
  tags: phantomjs

- name: PhantomJS | Systemd PhantomJS
  become: yes
  template: src=systemd/phantomjs.service.j2 dest=/lib/systemd/system/phantomjs.service
  when: ansible_distribution_version == '16.04'
  tags: phantomjs

- name: PhantomJS | Start PhantomJS
  become: yes
  service: name=phantomjs enabled=yes state=restarted
  tags: phantomjs
